use std::io::{BufWriter, Write};
use std::path::Path;

use anyhow::{Context, Result};

use crate::mesh::TriMesh;

fn color_u8(c: f32) -> u8 {
    (c.clamp(0.0, 1.0) * 255.0).round() as u8
}

/// Binary little-endian PLY with positions, normals, vertex colors, faces.
pub fn write_ply(mesh: &TriMesh, path: &Path) -> Result<()> {
    let file = std::fs::File::create(path)
        .with_context(|| format!("Creating {}", path.display()))?;
    let mut w = BufWriter::new(file);

    write!(
        w,
        "ply\nformat binary_little_endian 1.0\n\
         comment generated by meshsplat\n\
         element vertex {}\n\
         property float x\nproperty float y\nproperty float z\n\
         property float nx\nproperty float ny\nproperty float nz\n\
         property uchar red\nproperty uchar green\nproperty uchar blue\n\
         element face {}\n\
         property list uchar uint vertex_indices\n\
         end_header\n",
        mesh.num_vertices(),
        mesh.num_triangles()
    )?;

    for i in 0..mesh.num_vertices() {
        let p = mesh.positions[i];
        let n = mesh.normals[i];
        let c = mesh.colors[i];
        for v in [p.x, p.y, p.z, n.x, n.y, n.z] {
            w.write_all(&v.to_le_bytes())?;
        }
        w.write_all(&[color_u8(c[0]), color_u8(c[1]), color_u8(c[2])])?;
    }
    for tri in mesh.indices.chunks_exact(3) {
        w.write_all(&[3u8])?;
        for &i in tri {
            w.write_all(&i.to_le_bytes())?;
        }
    }
    w.flush()?;
    Ok(())
}

/// Wavefront OBJ. Vertex colors use the widely-supported `v x y z r g b`
/// extension (Blender, MeshLab, CloudCompare all read it).
pub fn write_obj(mesh: &TriMesh, path: &Path) -> Result<()> {
    let file = std::fs::File::create(path)
        .with_context(|| format!("Creating {}", path.display()))?;
    let mut w = BufWriter::new(file);

    writeln!(w, "# generated by meshsplat")?;
    for i in 0..mesh.num_vertices() {
        let p = mesh.positions[i];
        let c = mesh.colors[i];
        writeln!(
            w,
            "v {} {} {} {} {} {}",
            p.x, p.y, p.z, c[0], c[1], c[2]
        )?;
    }
    for n in &mesh.normals {
        writeln!(w, "vn {} {} {}", n.x, n.y, n.z)?;
    }
    for tri in mesh.indices.chunks_exact(3) {
        // OBJ indices are 1-based.
        writeln!(
            w,
            "f {a}//{a} {b}//{b} {c}//{c}",
            a = tri[0] + 1,
            b = tri[1] + 1,
            c = tri[2] + 1
        )?;
    }
    w.flush()?;
    Ok(())
}

/// Minimal valid glTF 2.0 binary (.glb): POSITION + NORMAL + COLOR_0 + indices.
pub fn write_glb(mesh: &TriMesh, path: &Path) -> Result<()> {
    // Binary buffer: positions, normals, colors (f32x3 each), then u32 indices.
    let nv = mesh.num_vertices();
    let mut bin: Vec<u8> = Vec::with_capacity(nv * 36 + mesh.indices.len() * 4);

    let mut pos_min = [f32::INFINITY; 3];
    let mut pos_max = [f32::NEG_INFINITY; 3];
    for p in &mesh.positions {
        for (i, v) in [p.x, p.y, p.z].into_iter().enumerate() {
            pos_min[i] = pos_min[i].min(v);
            pos_max[i] = pos_max[i].max(v);
            bin.extend_from_slice(&v.to_le_bytes());
        }
    }
    let normals_offset = bin.len();
    for n in &mesh.normals {
        for v in [n.x, n.y, n.z] {
            bin.extend_from_slice(&v.to_le_bytes());
        }
    }
    let colors_offset = bin.len();
    for c in &mesh.colors {
        for v in c {
            bin.extend_from_slice(&v.to_le_bytes());
        }
    }
    let indices_offset = bin.len();
    for i in &mesh.indices {
        bin.extend_from_slice(&i.to_le_bytes());
    }
    while bin.len() % 4 != 0 {
        bin.push(0);
    }

    let json = serde_json::json!({
        "asset": { "version": "2.0", "generator": "meshsplat" },
        "scene": 0,
        "scenes": [{ "nodes": [0] }],
        "nodes": [{ "mesh": 0 }],
        "meshes": [{
            "primitives": [{
                "attributes": { "POSITION": 0, "NORMAL": 1, "COLOR_0": 2 },
                "indices": 3,
                "mode": 4
            }]
        }],
        "buffers": [{ "byteLength": bin.len() }],
        "bufferViews": [
            { "buffer": 0, "byteOffset": 0, "byteLength": normals_offset, "target": 34962 },
            { "buffer": 0, "byteOffset": normals_offset, "byteLength": colors_offset - normals_offset, "target": 34962 },
            { "buffer": 0, "byteOffset": colors_offset, "byteLength": indices_offset - colors_offset, "target": 34962 },
            { "buffer": 0, "byteOffset": indices_offset, "byteLength": mesh.indices.len() * 4, "target": 34963 }
        ],
        "accessors": [
            { "bufferView": 0, "componentType": 5126, "count": nv, "type": "VEC3",
              "min": pos_min, "max": pos_max },
            { "bufferView": 1, "componentType": 5126, "count": nv, "type": "VEC3" },
            { "bufferView": 2, "componentType": 5126, "count": nv, "type": "VEC3" },
            { "bufferView": 3, "componentType": 5125, "count": mesh.indices.len(), "type": "SCALAR" }
        ]
    });
    let mut json_bytes = serde_json::to_vec(&json)?;
    while json_bytes.len() % 4 != 0 {
        json_bytes.push(b' ');
    }

    let total = 12 + 8 + json_bytes.len() + 8 + bin.len();
    let file = std::fs::File::create(path)
        .with_context(|| format!("Creating {}", path.display()))?;
    let mut w = BufWriter::new(file);
    // GLB header.
    w.write_all(b"glTF")?;
    w.write_all(&2u32.to_le_bytes())?;
    w.write_all(&(total as u32).to_le_bytes())?;
    // JSON chunk.
    w.write_all(&(json_bytes.len() as u32).to_le_bytes())?;
    w.write_all(b"JSON")?;
    w.write_all(&json_bytes)?;
    // Binary chunk.
    w.write_all(&(bin.len() as u32).to_le_bytes())?;
    w.write_all(b"BIN\0")?;
    w.write_all(&bin)?;
    w.flush()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use glam::Vec3;

    fn tiny_mesh() -> TriMesh {
        TriMesh {
            positions: vec![Vec3::ZERO, Vec3::X, Vec3::Y],
            normals: vec![Vec3::Z; 3],
            colors: vec![[1.0, 0.0, 0.0]; 3],
            indices: vec![0, 1, 2],
        }
    }

    #[test]
    fn glb_structure_is_valid() {
        let dir = std::env::temp_dir().join("msplat-test-glb");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("tiny.glb");
        write_glb(&tiny_mesh(), &path).unwrap();

        let bytes = std::fs::read(&path).unwrap();
        assert_eq!(&bytes[0..4], b"glTF");
        let total = u32::from_le_bytes(bytes[8..12].try_into().unwrap()) as usize;
        assert_eq!(total, bytes.len(), "GLB total length mismatch");
        let json_len = u32::from_le_bytes(bytes[12..16].try_into().unwrap()) as usize;
        let json: serde_json::Value =
            serde_json::from_slice(&bytes[20..20 + json_len]).unwrap();
        assert_eq!(json["asset"]["version"], "2.0");
    }

    #[test]
    fn ply_roundtrip_header() {
        let dir = std::env::temp_dir().join("msplat-test-ply");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("tiny.mesh.ply");
        write_ply(&tiny_mesh(), &path).unwrap();
        let bytes = std::fs::read(&path).unwrap();
        let header = String::from_utf8_lossy(&bytes[..400.min(bytes.len())]);
        assert!(header.starts_with("ply\nformat binary_little_endian"));
        assert!(header.contains("element vertex 3"));
        assert!(header.contains("element face 1"));
    }
}
